//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "novels")]
pub struct Model {
    pub country: String,
    pub rating: Option<i32>,
    pub status: Option<String>,
    pub notes: String,
    pub date_modified: DateTime,
    pub chapter: String,
    pub tags: Json,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i32,
    pub title: String,
    pub date_started: Option<DateTime>,
    pub date_completed: Option<DateTime>,
    pub provider: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
