name: backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '!backend/migration/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '!backend/migration/**'

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy --tests -- -Dclippy::all -Dclippy::pedantic
